### ISSUE TITLE
Improve error message if outputDirectory property is missing

### ISSUE THREAD

**Issue by lucimihai** [unbroken-dome/gradle-xjc-plugin#15]
I'm trying to call the xic plugin twice in the build script as follows:

import org.unbrokendome.gradle.plugins.xjc.XjcGenerate

task requestXjcGenerate(type: XjcGenerate){
    source = fileTree('src/main/resources/schema/') { include '*IN*.xsd' }
    targetPackage = "org.req"
}

task responseXjcGenerate(type: XjcGenerate){
    source = fileTree('src/main/resources/schema/') { include '*OUT*.xsd' }
    targetPackage = "org.res"
}

When I run the any of the tasks, I get : Cannot invoke method toPath() on null object

**Comment by tkrullmann** [comment]
Hi @lucimihai,

please set the property `outputDirectory` on the tasks. 

I will try to make the reporting better if that property is missing, so the plugin tells you more clearly what's wrong.
