### ISSUE TITLE
No value has been specified for property 'urlSources'.

### ISSUE THREAD

**Issue by eszikk** [unbroken-dome/gradle-xjc-plugin#17]
I am getting a following error when i run the plugin `No value has been specified for property 'urlSources'.` 

I have a wsdl on my local filesystem what should I do?

As I see `urlSources` only accepts files containing urls not wsdls.

**Comment by tkrullmann** [comment]
Hi,

this should be fixed by making the `urlSources` property of the task `@Optional`.

**Comment by tkrullmann** [comment]
About the WSDL code generation: Usually you would use another tool called `wsimport`, which also generates the service interfaces, not just the schema classes. XJC has a special flag `-wsdl` which you can activate like this.

```groovy
xjcGenerate {
    // Make sure the WSDL files are included in source
    source = fileTree('src/main/schema') { include '*.wsdl' }

    // Add -wsdl to extraArgs
    extraArgs = [ '-wsdl' ]
}
```
