### ISSUE TITLE
Add Extra Details To README For equals()  and toString()

### ISSUE THREAD

**Issue by opticyclic** [unbroken-dome/gradle-xjc-plugin#19]
The section in the README on **Using XJC plugins** says:

> XJC allows to hook into and extend the code-generation process by using plugins. A plugin might, for example, add equals() and toString() methods into generated classes.

It then correctly specifies how to modify the plugin classpath.

However, it then mentions unrelated args in the **Specifying extra arguments** section

> xjcGenerate {
>     extraArgs = [
>         '-Xcommons-lang',
>         '-Xfluent-api'
>     ]
> }

This should follow on from the example in the pevious section and say: 

    extraArgs = [
       '-Xequals',
       '-XtoString'
    ]

Also, the generated code will no longer compile unless the compile classpath is modified so you should mention that too:

    xjcClasspath 'org.jvnet.jaxb2_commons:jaxb2-basics:0.11.1'
    compile 'org.jvnet.jaxb2_commons:jaxb2-basics-runtime:0.11.1'

**Comment by tkrullmann** [comment]
Hi,

these were merely meant as examples so I deliberately chose different values in the documentation. Also, I would argue that setting the compile classpath is out of scope of this plugin. You'd have to remember that also when using XJC directly or a different stack on top of it.

But I will try to make the documentation more consistent if it's confusing.
