### ISSUE TITLE
Is there a possibility to have multiple xjcGenerate one build.gradle

### ISSUE THREAD

**Issue by rohanmukesh** [unbroken-dome/gradle-xjc-plugin#2]
Is there a possibility to have multiple xjcGenerate to support following:

We need to pick-up sub-folder and put the generated code in existing packages matching the existing calling code import commands.

We need to pick-up schemas from two folders and generate two packages

schemas/response/_.xsd --> ...schema.request._ package
schemas/response/_.xsd --> ...schema.response._ package
Going to the relevant sub-folder under the generated/ folder sub-tree.

   xjcGenerate //  first pairing
    {
       source = fileTree("$projectDir/src/main/resources/com/product/xsd") {
            include 'Request.xsd'
        }
        outputDirectory = file("$buildDir/generated-sources/jaxb")
        extraArgs = ["-Xsetters", "-Xsetters-mode=direct", "-Xfluent-api", "-Xbg", "-Xcommons-lang3"]
        targetPackage = "com.generated.request"
        
    }        
    xjcGenerate //  a second pairing
    {
       source = fileTree("$projectDir/src/main/resources/com/product/xsd") {
            include 'Response.xsd'
        }
        outputDirectory = file("$buildDir/generated-sources/jaxb")
        extraArgs = ["-Xsetters", "-Xsetters-mode=direct", "-Xfluent-api", "-Xbg", "-Xcommons-lang3"]
        targetPackage = "com.generated.response"
        
    }

**Comment by tkrullmann** [comment]
Hi @rohanmukesh,

you can define additional `XjcGenerate` tasks in the project by specifying the type (note the capital "X"):

```groovy
xjcGenerate {
    // ...
}

task xjcGenerateOther(type: XjcGenerate) {
    // ...
}
```

Let me know if that works for you!
