### ISSUE TITLE
Deprecation warnings 

### ISSUE THREAD

**Issue by douglassparker** [unbroken-dome/gradle-xjc-plugin#23]
When building with gradle 6.5 and --warning-mode all, the following warnings are generated:

> Type 'XjcGenerate': setter method 'setClasspath()' should not be annotated with: @Internal. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
> Property 'contentForWildcard' has redundant getters: 'getContentForWildcard()' and 'isContentForWildcard()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
> Property 'enableIntrospection' has redundant getters: 'getEnableIntrospection()' and 'isEnableIntrospection()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
> Property 'extension' has redundant getters: 'getExtension()' and 'isExtension()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
> Property 'includeEpisodeFileInJar' has redundant getters: 'getIncludeEpisodeFileInJar()' and 'isIncludeEpisodeFileInJar()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
> Property 'includeInMainCompilation' has redundant getters: 'getIncludeInMainCompilation()' and 'isIncludeInMainCompilation()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
> Property 'noFileHeader' has redundant getters: 'getNoFileHeader()' and 'isNoFileHeader()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
> Property 'packageLevelAnnotations' has redundant getters: 'getPackageLevelAnnotations()' and 'isPackageLevelAnnotations()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
> Property 'quiet' has redundant getters: 'getQuiet()' and 'isQuiet()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
> Property 'readOnly' has redundant getters: 'getReadOnly()' and 'isReadOnly()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
> Property 'strictCheck' has redundant getters: 'getStrictCheck()' and 'isStrictCheck()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
> Property 'verbose' has redundant getters: 'getVerbose()' and 'isVerbose()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
> Property 'outputDirectory' has @Input annotation used on property of type 'File'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.5/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.

Just wanted to make sure you are aware that changes will be needed for Gradle 7. Kudos for a great plugin.

**Comment by tkrullmann** [comment]
Version 2.0 of the plugin is a complete rewrite in Kotlin, building with `--warning-mode=all` does not display any warnings (building with Gradle 6.6.1) so I'll consider this fixed. Thanks for the heads-up.
