### ISSUE TITLE
Example usage of new version

### ISSUE THREAD

**Issue by renjfk** [unbroken-dome/gradle-xjc-plugin#24]
Hi there,

Been trying to figure out for a while to setup multiple configuration for different sets of schemas but no use. Could you possibly help with achieving similar result with following configuration?

```gradle
xjcGenerate {
    source = files('schema1.xsd')
    bindingFiles = files('binding1.xml')
    targetPackage = 'com.example1'
}

task xjcGenerateCustom(type: XjcGenerate) {
    source = files('schema2.xsd', 'schema3.xsd')
    targetPackage = 'com.example2'
}
```

This kind of config doesn't work due to error `Cannot set the value of read-only property 'source' for task ':xjcGenerate' of type org.unbrokendome.gradle.plugins.xjc.XjcGenerate.`.

Thanks,
Soner.

**Comment by tkrullmann** [comment]
Hi,

you're right, the `source` and `bindingFiles` properties are now readonly, but they are of type `ConfigurableFileCollection` so you can use `source.from ...` instead of `source = ...` to achieve the same.

Better yet, consider putting these files into a separate source set so you won't have to set up an `XjcGenerate` task at all.

**Comment by renjfk** [comment]
I also have been trying to do that for a while but it's not able to pick my custom source set for some reason.

```gradle
sourceSets {
    main {
        xjcSchema { // this is working fine
            srcDir 'src/main/resources/xsd'
            includes = ['example1.xsd']
            xjcTargetPackage = 'com.example1'
        }
    }
    example2 { // but this is not being generated at all
        xjcSchema {
            srcDir 'src/main/resources/xsd'
            includes = ['example2.xsd']
            xjcTargetPackage = 'com.example2'
        }
    }
}
```

**Comment by tkrullmann** [comment]
Probably the tasks you're calling don't include compiling the `example2` source set. For example, when calling `gradle build` or `gradle assemble` then it will build the JAR, which only contains the `main` source set by default.

You can add additional source sets to the JAR quite easily:

```
jar {
    from sourceSets.example2.output
}
```

**Comment by renjfk** [comment]
That was the case indeed. Thanks for helping!

Here's my final config for future reference:

```gradle
sourceSets {
    example2 {
        xjcSchema {
            srcDir 'src/main/resources/xsd'
            includes = ['example2.xsd']
            xjcTargetPackage = 'com.example2'
        }

        compileClasspath += sourceSets.main.compileClasspath
        runtimeClasspath += sourceSets.main.runtimeClasspath
    }

    main {
        xjcSchema {
            srcDir 'src/main/resources/xsd'
            includes = ['example1.xsd']
            xjcTargetPackage = 'com.example1'
        }

        compileClasspath += example2.output
        runtimeClasspath += example2.output
    }
}
```

**Comment by rost5000** [comment]
It would be nice to add this example to Doc: https://unbroken-dome.github.io/projects/gradle-xjc-plugin/

**Comment by MarkusWiland** [comment]
How could I for example bind a file to these too?
