### ISSUE TITLE
"includeInMainCompilation" setting in version 2

### ISSUE THREAD

**Issue by probststefan** [unbroken-dome/gradle-xjc-plugin#25]
I could not figure out how to set the option "includeInMainCompilation" in version 2.0.0. I would like to achieve the following:

`
    xjc {
        includeInMainCompilation = false
    }`

Thx for the great work!

**Comment by tkrullmann** [comment]
Hi,
This flag was dropped in 2.0, its purpose was to support different source sets, which is now an integral part of the plugin.

Best approach is to create a separate source set and put your xjc sources in there. If you really want to _only_ generate code but not compile it, then disabling the `compileJava` task for that source set should do the trick.
