### ISSUE TITLE
Unable to get plain setup to work, based on documentation

### ISSUE THREAD

**Issue by spudtheimpaler** [unbroken-dome/gradle-xjc-plugin#26]
Hi,

I am trying to get a very basic setup working based on the documentation here: https://unbroken-dome.github.io/projects/gradle-xjc-plugin/

It suggests that a basic setup as below should be enough to get a working example:

```
plugins {
    id 'org.unbroken-dome.xjc' version '2.0.0'
}

apply plugin: 'java-library' // This isn't actually in the docs, for us gradle newbies this may help

dependencies {
    implementation 'javax.xml.bind:jaxb-api:2.3.0'
}
```

I have my schema file in the suggested default location of `src/main/schema`

When attempting to run the above, my gradle build fails with 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':project-name:xjcGenerate'.
> A failure occurred while executing org.unbrokendome.gradle.plugins.xjc.work.xjc23.XjcGeneratorWorkAction
   > com/sun/xml/bind/Utils
```

I expect there is a missing dependency, however the jaxb dependencies are a bit of a minefield, so I am finding out. Is it possible to update the documentation with whatever this missing dependency may be (or a suggestion if there are options?)

Or perhaps my naivety is showing, and there is a different issue at play? :)

Many thanks in advance,
Mitch.

**Comment by nickdul** [comment]
Java 11 and xjcVersion = '2.3'
for some reason plugin cannot lookup `com.sun.xml.bind.Utils` class
I tried to add `com.sun.xml.bind:jaxb-impl:2.3.3` to classpath via `implementation` and `xjcClasspath` but without luck

@tkrullmann any help is appreciated

```
Caused by: java.lang.NoClassDefFoundError: com/sun/xml/bind/Utils
        at com.sun.tools.xjc.Options.<clinit>(Options.java:156)
        at org.unbrokendome.gradle.plugins.xjc.work.common.AbstractXjcGeneratorWorkAction.buildOptions(AbstractXjcGeneratorWorkAction.kt:68)
        at org.unbrokendome.gradle.plugins.xjc.work.common.AbstractXjcGeneratorWorkAction.execute(AbstractXjcGeneratorWorkAction.kt:31)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
```

**Comment by nickdul** [comment]
well, the problem was with transitive dependencies for `xjcTool`  
in my project `com.sun.xml.bind:jaxb-impl` was silently switched to version `2.3.0` which was lead to exception above
``` 
xjcTool
\--- com.sun.xml.bind:jaxb-xjc:2.3.3
     \--- com.sun.xml.bind:jaxb-impl:2.3.3 -> 2.3.0
```

setting `xjcTool` explicitly solves the problem:
``` gradle
    xjcTool 'com.sun.xml.bind:jaxb-xjc:2.3.3'
    xjcTool 'com.sun.xml.bind:jaxb-impl:2.3.3'
```

**Comment by rawslaw** [comment]
thank you @nickdul!  I have been banging my head on this for a few days, thinking a library was wrong or missing in my local artifactory.
### Symptom
`xjcTool` dependency tree was not reporting the missing (or overridden) transitive dependency 

```
xjcTool
\--- com.sun.xml.bind:jaxb-xjc:2.3.3
```
yet `xjcGenerate` continued to fail.
```
Execution failed for task ':xjcGenerate'.
> A failure occurred while executing org.unbrokendome.gradle.plugins.xjc.work.xjc23.XjcGeneratorWorkAction
   > com/sun/xml/bind/Utils
```
despite `jaxb-impl:2.3.3` is present in my artifactory.
### Solution

> 
> ```groovy-gradle
>     xjcTool 'com.sun.xml.bind:jaxb-xjc:2.3.3'
>     xjcTool 'com.sun.xml.bind:jaxb-impl:2.3.3'
> ```

Explicitly setting `xjcTool` as you describe resolved the problem without importing any additional libraries to artifactory and produces this new dependency tree:

```
xjcTool
+--- com.sun.xml.bind:jaxb-xjc:2.3.3
\--- com.sun.xml.bind:jaxb-impl:2.3.3
```
