### ISSUE TITLE
outputDirectory convention not applied

### ISSUE THREAD

**Issue by thodt-md** [unbroken-dome/gradle-xjc-plugin#4]
With this configuration

```
xjcGenerate {
  verbose = true
  extraArgs = [
      '-no-header',
      '-Xxew', '-Xxew:instantiate lazy', '-Xvalue-constructor'
  ]
}
```

I get the following error

```
:xjcGenerate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':xjcGenerate'.
> No value has been specified for property 'packageOutputDirectory'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

I use Gradle 3.5.1, XJC plugin 1.1.2 and a couple of XJC extensions (JAXB2 Commons Value Constructor and XEW plugin). The workaround is to manually specify `outputDirectory = project.file("${project.buildDir}/xjc/generated-sources")` in the configuration block.

But this kind of defeats the convention purpose?

**Comment by tkrullmann** [comment]
Hi Igor, thanks for the report!
This seems to be a regression that was introduced with 1.1.2. The task uses the field `outputDirectory` directly instead of calling `getOutputDirectory()`, thus circumventing the convention mapping.
