### ISSUE TITLE
different ExtraArgs for different schemas

### ISSUE THREAD

**Issue by bghost4** [unbroken-dome/gradle-xjc-plugin#5]
is there a way to have separate tasks or ExtraArgs for different schemas? I tried:: 
task justOneSchema(type: xjcGenerate) { }
I get: org.unbrokendome.gradle.plugins.xjc.XjcGenerate_Decorated cannot be cast to java.lang.Class

This is probably already possible, but I couldn't find any examples. 
if it is already possible could you add an example to the Readme?

**Comment by bghost4** [comment]
taking the advice of issue #2 using task name(type: XjcGenerate) I get:
Could not get unknown property 'XjcGenerate' for root project 'xxx' of type org.gradle.api.Project.

**Comment by tkrullmann** [comment]
Hi,
could you try the fully qualified name of the task class?
i.e.
```groovy
task justOneSchema(type: org.unbrokendome.gradle.plugins.xjc.XjcGenerate) { }
```

You could also try adding an import statement to the build script if you need this more than once.

I know this is quite ugly and will probably provoke a warning from the IDE. I think at least with IntelliJ IDEA, classes from the plugins are not directly visible anymore with the new `plugins { }` DSL.

I could imagine two ways to make this more convenient:
1. Store `XjcGenerate` as a `Class` property in the `xjc` extension. Feels a bit like a hack, but would look nice:
```groovy
task justOneSchema(type: xjc.Generate) { }
```

2. Add a method to the `xjc` extension that creates a `XjcGenerate` task:
```groovy
xjc.generateTask(name: 'justOneSchema') { }
```

**Comment by jorge-senger** [comment]
I'm trying this approach but I got the following error:

Caused by: java.lang.NullPointerException: Cannot get property 'empty' on null object
        at org.unbrokendome.gradle.plugins.xjc.XjcGenerate$_closure1.doCall(XjcGenerate.groovy:92)
        at org.gradle.api.specs.internal.ClosureSpec.isSatisfiedBy(ClosureSpec.java:32)

This is my task:

task xjc_SPS(type: org.unbrokendome.gradle.plugins.xjc.XjcGenerate) {
    source = fileTree('src/main/resources/xxx//') { include 'mySchema.xsd' }
    outputDirectory = file('generated-sources/')
    targetPackage = 'com.xxx'
}
