### ISSUE TITLE
Catalog Resolution classpath to resolve schemas in same build

### ISSUE THREAD

**Issue by tjanu** [unbroken-dome/gradle-xjc-plugin#7]
Hi,

I have a setup where I use a catalog resolver for schema resolution, with two projects:
- project A contains a schema in classpath location 'xsd/common.xsd' and gets packaged including episode file and the catalog file
- project B contains two schemas:
  - a.xsd importing just common.xsd
  - b.xsd importing common.xsd and a.xsd

The catalog file in project A maps `http://www.example.com/xsd` to `classpath:xsd/` using REWRITE_SYSTEM. The imports in `a.xsd` and `b.xsd` of course use `http://www.example.com/xsd/{common,a}.xsd` as the schema locations.

The problems started when I added b.xsd: The classpath resolution for common.xsd works fine, but the import of `a.xsd` for `b.xsd` cannot be resolved.

With debugging output, I can see that he correctly tries to resolve `a.xsd` via `maven:::!xsd/a.xsd` while loading, but he can't find it.

So far I tried:
- letting the `CatalogResolutionClasspath` extend configuration `runtime`
- adding `files('src/main/resources')` to the `CatalogResolutionClasspath`

but none of these work, so I reimplemented the lookup procedure in `MavenUriResolver` directly in gradle as a task to take a look at the steps taken:

    task tryResolve {
        doLast {
            def uri = new URI('maven:::!xsd/a.xsd')
            def schemeSpecific = uri.schemeSpecificPart
            println "URI: " + uri + " - schemeSpecific: " + schemeSpecific
            def dep = org.unbrokendome.gradle.plugins.xjc.resolver.DependencyResource.parse(schemeSpecific)
            println "dependency resource: " + dep
            def arts = configurations.jaxb.resolvedConfiguration.lenientConfiguration.getArtifacts(dep)
            println "Artifacts: " + arts
            def fAOne = arts.findAll { dep.classifier == null || it.classifier == dep.classifier }
            println "findAllOne: " + fAOne
            def fATwo = fAOne.findAll { dep.ext == null || it.ext == dep.ext }
            println "findAllTwo: " + fATwo
            if (dep.path) {
                println "Dependency has a path"
                def url = fATwo*.file*.toURI()*.toURL()
                println "URL" + url
            } else {
                println "Dependency does not have a path"
                println "URI: " + fATwo*.file*.toURI().first()
            }
        } 
    }

which leads to this output in both cases:

    URI: maven:::!xsd/a.xsd - schemeSpecific: ::!xsd/a.xsd
    dependency resource: org.unbrokendome.gradle.plugins.xjc.resolver.DependencyResource(xsd/a.xsd)
    Artifacts: [common-xml.jar (project :common-xml)]
    findAllOne: [common-xml.jar (project :common-xml)]
    findAllTwo: [common-xml.jar (project :common-xml)]
    Dependency has a path
    URL: [file:/[...]/common-xml/build/libs/common-xml-0.1.jar]

When I substitute `a.xsd` in the task with the working `common.xsd` the output is the same, but of course that one can be found in the jar file by the URLClassLoader instantiated there.

Any ideas on how to get this working?

Thanks in advance.

**Comment by tkrullmann** [comment]
Hi,
I would recommend to use a separate sub-path in the namespace for each project, so you can be more specific as to what should be resolved from the classpath and what not.
The only workaround I could imagine would be to use a different source set for the two schemas, so when the imports of b.xsd are resolved then a.xsd is already on the classpath.
