### ISSUE TITLE
Can't configure paths neither generate sources

### ISSUE THREAD

**Issue by pilak** [unbroken-dome/gradle-xjc-plugin#8]
Hello,

I'm facing multiple issues while trying to generate classes from my _xsd_ file with the plugin gradle-xjc-plugin (v1.2.0)
Although I'm clearly specifying _xsd_ directory with declaration below, the plugin is still looking at src/main/schema folder in  order to retrieve the _xsd_

``` groovy
xjcGenerate {
    source = fileTree('src/main/resources') { include '*.xsd' }
    catalogs = fileTree('src/main/schema') { include 'catalog.xml' }
}

```
But still, I have the error below when launching `./gradlew build` :

> Excluding [xml-apis:xml-apis]
> Excluding []
> Excluding []
> Task ':xjcGenerate' is not up-to-date because:
>   Task has failed previously.
> Property "http://javax.xml.XMLConstants/property/accessExternalSchema" is not supported by used JAXP implementation.

Please advise

**Comment by tkrullmann** [comment]
Hi @pilak,
I've tried to put the schema in src/main/resources and it worked just fine... could you post a sample project and/or `build.gradle` file that would give some more context?

As for the second problem, which JDK version are you running your Gradle build with? According to [this page](https://docs.oracle.com/javase/tutorial/jaxp/properties/properties.html) the `accessExternalSchema` property was added in JAXP 1.5, so it should be available with JDK 7u40+ or JDK 8+ ([reference](https://docs.oracle.com/javase/8/docs/technotes/guides/xml/jaxp/index.html)).

**Comment by harsheel87** [comment]
Hi @tkrullmann , thanks for the useful comment. The links you provided are for Oracle JDK. Could the error occur due to using OpenJDK 8 (on Linux)?

**Comment by tkrullmann** [comment]
I tried this on several versions of OpenJDK 8, I couldn't reproduce it with any. Could you please post which JDK version you're using, and provide a sample build script that gives you the error?
